# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a9fb07c92b20683e18e840bdd5fcf19aa9e64eabe5948faa20d56d011d36b3d1bf91eb99a89606837fed73a66608723299d7f608d1abfff1a4040f9a03a925

test:
  secret_key_base: 55f8fcb2080da35ddf441642d335300e33f931c77aa8d1371f4143f0cf10326ee6cc58e92838bf981df5aa6160327658d038799a5de83753aef474cc3f472023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
